api_platform:
    exception_to_status:
        App\Exception\UserAlreadyActiveException: 'HTTP_BAD_REQUEST'
        App\Exception\BadActivationCodeException: 'HTTP_BAD_REQUEST'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header