api_platform:
    # The title of the API.
    title: 'Api for application Roman'
    # The description of the API.
    description: 'This application helps user  to write their romans.'
    # The version of the API.
    version: '0.0.0'

    # The list of exceptions mapped to their HTTP status code.
    exception_to_status:
        App\Exception\UserAlreadyActiveException: 400
        App\Exception\BadActivationCodeException: 400
        App\Exception\UserNotFoundException: 404
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: 400 # Or a `Symfony\Component\HttpFoundation\Response`'s constant
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

    mapping:
        # The list of paths with files or directories where the bundle will look for additional resource files.
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Request'

    swagger:
        # The swagger api keys.
        api_keys:
            apiKey:
                name: Authorization
                type: header

    ##########################################################################
    # ALL OTHER ARE SET TO DEFAULT VALUE
    # @see https://github.com/api-platform/docs/blob/2.4/core/configuration.md
    ##########################################################################
